apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tasksystem

resources:
  - ../../base

secretGenerator:
  - name: tasksystem-secrets
    envs:
      - secrets.env

generatorOptions:
  labels:
    app.kubernetes.io/name: tasksystem
    app.kubernetes.io/component: configuration
