apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tasksystem

resources:
  - ../../base

secretGenerator:
  - name: tasksystem-secrets
    envs:
      - secrets.env

generatorOptions:
  labels:
    app.kubernetes.io/name: tasksystem
    app.kubernetes.io/component: configuration
    
images:
  - name: ghcr.io/aurimasg1/tasksystem
    newTag: sha-ea5b03c05ca6b047e6100800a158d6085fe259a6
