apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tasksystem-api-data-protection
  namespace: tasksystem
  labels:
    app.kubernetes.io/name: tasksystem
    app.kubernetes.io/component: api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
