apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - mysql-service.yaml
  - mysql-statefulset.yaml
  - migration-job.yaml
  - api-data-protection-pvc.yaml
  - api-deployment.yaml
  - api-service.yaml
