apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - mysql-service.yaml
  - mysql-statefulset.yaml
  - migration-job.yaml
  - api-data-protection-pvc.yaml
  - api-deployment.yaml
  - api-service.yaml
  - gateway.yaml
  - api-httproute.yaml
  - mysql-networkpolicy.yaml
  - api-hpa.yaml

configMapGenerator:
  - name: tasksystem-config
    literals:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - Jwt__Issuer=TaskSystemAPI
      - MYSQL_DATABASE=tasksystem
      - MYSQL_USER=tasksystem_app

generatorOptions:
  labels:
    app.kubernetes.io/name: tasksystem
    app.kubernetes.io/component: configuration
